/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProxyRunner;

import javax.swing.JOptionPane;

/**
 *
 * @author Temporary
 */
public class ProxyAddFrame extends javax.swing.JFrame {

    ProxyBasic proxy;
    private ProxyBasic proxyBasic;
    private ProxyFinal proxyFinal;
    private String networkSSID;
    /**
     * Creates new form ProxyAddFrame
     */
    public ProxyAddFrame() {
        initComponents();
        ssidName.setText(networkSSID);
        revalidate();
        repaint();
    }
    
    public ProxyAddFrame(ProxyBasic pb){
        initComponents();
        this.proxyBasic = pb;
        this.networkSSID = pb.getWifiSSID();
        ssidName.setText(networkSSID);
        revalidate();
        repaint();
    }
    
    public ProxyAddFrame(ProxyFinal pf){
        initComponents();
        this.proxyFinal = pf;
        this.networkSSID = pf.getWifiSSID();
        ssidName.setText(networkSSID);
        revalidate();
        repaint();
    }
    
    public ProxyAddFrame(String networkSSID){
        initComponents();
        this.networkSSID = networkSSID;
        ssidName.setText(this.networkSSID);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ssidName = new javax.swing.JLabel();
        adsBoolean = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        inputProxyScript = new javax.swing.JTextField();
        inputProxyAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputProxyPort = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        confirmProxy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Internet settings");

        jLabel1.setText("Automatically detect settings");

        jLabel2.setText("Automatic configuration script");

        ssidName.setText("SSID NAME");

        adsBoolean.setText("Enabled");

        jLabel4.setText("Proxy Server Address");

        jLabel3.setText("Proxy Server Port");

        inputProxyPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputProxyPortActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        confirmProxy.setText("Confirm");
        confirmProxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmProxyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(adsBoolean))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(inputProxyScript, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputProxyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(ssidName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(cancel)
                .addGap(43, 43, 43)
                .addComponent(confirmProxy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ssidName)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adsBoolean)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(inputProxyScript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputProxyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addComponent(inputProxyPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(confirmProxy))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputProxyPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputProxyPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputProxyPortActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void confirmProxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmProxyActionPerformed
        //get information entered and add to arraylist.
        boolean enabled;
        String proxyScript;
        String proxyAddress;
        int proxyPort = -1;
        
        enabled = adsBoolean.isSelected();
        proxyScript = inputProxyScript.getText();
        proxyAddress = inputProxyAddress.getText();
        try{
            if(!inputProxyPort.getText().equals("")) {
                proxyPort = Integer.valueOf(inputProxyPort.getText());
            }else{
                proxyPort = -1;
            }//set the value of the proxy port.
            if((proxyPort > 65535 || proxyPort < 0) && !proxyAddress.equals("")){
                System.out.println(proxyPort);
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid port number. A");
                //NEED TO MAKE IT SO THAT IT DOES DISPOSE OF THE FRAME
            }
            else if(proxyAddress.equals("") && proxyPort >= 0){
                System.out.println(proxyPort);
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid proxy address. B");
            }else{//THIS ELSE NEEDS TO BE MADE SO THAT THE ABOVE IF FUNCTIONS WORK BETTER.
                if(!proxyScript.equals("")){
                    if(!proxyAddress.equals("")){
                        if(networkSSID != null){
                            proxy = new ProxyFinal(networkSSID, proxyAddress, proxyPort, proxyScript, enabled);
                            dispose();
                        }      
                    }else{
                        proxy = new ProxyScript(networkSSID, proxyScript, enabled);
                        dispose();
                    }
                }else if(proxyScript.equals("")){
                    if(proxyAddress.equals("")){
                        proxy = new ProxyAdvanced(networkSSID, proxyAddress, proxyPort, enabled);
                        dispose();
                    }else if(!proxyAddress.equals("")){
                        proxy = new ProxyAuto(networkSSID, enabled);
                        dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Please select valid proxy settings.");
                }
            }
            //print out settings.
        System.out.println(enabled + " " + proxyScript + " " + proxyAddress + " " + proxyPort);
        }catch(NumberFormatException e){
            if(!proxyScript.equals("") && !proxyAddress.equals("")){
                proxy = new ProxyAuto(networkSSID, enabled);
                dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid port number. CATCH");
                e.printStackTrace();
            }
            System.out.println("FAILED");
        }
        
        
    }//GEN-LAST:event_confirmProxyActionPerformed

    public ProxyBasic getProxy() {
        return proxy;
    }

    public void setProxy(ProxyFinal proxy) {
        this.proxy = proxy;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProxyAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProxyAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProxyAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProxyAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProxyAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adsBoolean;
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirmProxy;
    private javax.swing.JTextField inputProxyAddress;
    private javax.swing.JTextField inputProxyPort;
    private javax.swing.JTextField inputProxyScript;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ssidName;
    // End of variables declaration//GEN-END:variables
}
